#!/usr/bin/env python3
"""Generate remaining UI element showcase pages - batch 2."""
import os

BASE_DIR = "/workspace/html-clone/templates/html"

def page_head(title, extra_css=""):
    return f'''<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} — UI Elements</title>
<style>::-webkit-scrollbar{{width:6px;height:6px}}::-webkit-scrollbar-track{{background:transparent}}::-webkit-scrollbar-thumb{{background:#cbd5e1;border-radius:3px}}::-webkit-scrollbar-thumb:hover{{background:#94a3b8}}@media(prefers-reduced-motion:reduce){{*,*::before,*::after{{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}}}</style>
<link rel="stylesheet" href="tailwind-production.css">
<link rel="stylesheet" href="pro-styles.css">
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<style>
.component-item{{border:1px solid #e5e7eb;border-radius:.75rem;overflow:hidden;background:#fff;transition:box-shadow .2s,border-color .2s}}.component-item:hover{{box-shadow:0 4px 12px rgba(0,0,0,.08);border-color:#cbd5e1}}
.dark .component-item{{border-color:#374151;background:#1f2937}}.dark .component-item:hover{{border-color:#4b5563;box-shadow:0 4px 12px rgba(0,0,0,.3)}}
.component-item-header{{padding:1rem 1.25rem;border-bottom:1px solid #f3f4f6;display:flex;align-items:center;justify-content:space-between}}.dark .component-item-header{{border-color:#374151}}
.component-item-preview{{padding:1.5rem;display:flex;flex-wrap:wrap;gap:.75rem;align-items:flex-start;min-height:80px}}
.component-item-actions{{padding:.75rem 1.25rem;border-top:1px solid #f3f4f6;display:flex;gap:.5rem}}.dark .component-item-actions{{border-color:#374151}}
{extra_css}
</style>
</head>
<body class="bg-gray-50 text-gray-800 font-sans dark:bg-gray-900 dark:text-gray-100">
<div id="sidebar-overlay" class="fixed inset-0 bg-black/40 z-40 hidden lg:hidden" onclick="window.toggleSidebar&&toggleSidebar()"></div>
<div class="flex h-screen overflow-hidden">
<div id="sidebar-container"></div>
<div class="flex-1 flex flex-col overflow-hidden">
<div id="header-container"></div>
<main class="flex-1 overflow-y-auto overflow-x-hidden px-4 md:px-6 2xl:px-10 py-6" tabindex="-1">
<div class="mx-auto w-full max-w-screen-2xl">'''

def page_foot(extra_js=""):
    return f'''</div></main></div></div>
<script src="common-loader.js"></script><script src="common-sidebar.js"></script><script src="common-header.js"></script><script src="app-shell.js"></script>
<script>document.addEventListener('DOMContentLoaded',function(){{document.querySelectorAll('[data-counter]').forEach(function(el){{var target=parseInt(el.dataset.counter);var duration=1200;var startTime=null;function step(ts){{if(!startTime)startTime=ts;var p=Math.min((ts-startTime)/duration,1);el.textContent=Math.floor(p*target);if(p<1)requestAnimationFrame(step);else el.textContent=target;}}requestAnimationFrame(step);}});}});{extra_js}</script>
</body></html>'''

def ci(title, desc, category, cat_color, preview_html, source_code):
    src_escaped = source_code.replace('&', '&amp;').replace('"', '&quot;').replace('<', '&lt;').replace('>', '&gt;')
    return f'''<div class="component-item" data-category="{category}" data-title="{title}">
<div class="component-item-header"><div><h3 class="font-semibold text-gray-900 dark:text-white">{title}</h3><p class="text-xs text-gray-500 dark:text-gray-400 mt-0.5">{desc}</p></div><span class="text-[10px] font-medium px-2 py-0.5 rounded-full {cat_color}">{category.title()}</span></div>
<div class="component-item-preview" data-source-id="{title.lower().replace(' ','-').replace('/','')}" data-source-code="{src_escaped}">{preview_html}</div>
<div class="component-item-actions"><button class="text-xs font-medium text-gray-500 hover:text-blue-600 dark:text-gray-400 dark:hover:text-blue-400 flex items-center gap-1" onclick="openSourceViewer(this)"><svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"/></svg>View Source</button><button class="text-xs font-medium text-gray-500 hover:text-blue-600 dark:text-gray-400 dark:hover:text-blue-400 flex items-center gap-1" onclick="copySourceCode(this)"><svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"/></svg>Copy</button></div></div>'''

def wrap_page(title, desc, stats, categories, items_html, extra_css="", extra_js=""):
    stat_cards = ""
    for s in stats:
        val_attr = f' data-counter="{s["value"]}"' if isinstance(s['value'], int) else ''
        val_text = '0' if isinstance(s['value'], int) else s['value']
        stat_cards += f'''<div class="bg-white dark:bg-gray-800 rounded-xl border border-gray-100 dark:border-gray-700 p-5">
<div class="flex items-center justify-between mb-3"><span class="text-sm font-medium text-gray-500 dark:text-gray-400">{s['label']}</span><span class="w-8 h-8 rounded-lg {s['icon_bg']} flex items-center justify-center"><svg class="w-4 h-4 {s['icon_color']}" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="{s['icon_path']}"/></svg></span></div>
<p class="text-2xl font-bold text-gray-900 dark:text-white"{val_attr}>{val_text}</p><p class="text-xs text-green-600 font-medium mt-1">{s['sub']}</p></div>'''
    cat_btns = ""
    for i, (cat, label) in enumerate(categories):
        if i == 0:
            cat_btns += f'<button class="px-3 py-1.5 text-sm font-medium rounded-lg bg-blue-600 text-white shadow-sm" data-category="{cat}" onclick="initCategoryFilter(\'{cat}\',this)">{label}</button>'
        else:
            cat_btns += f'<button class="px-3 py-1.5 text-sm font-medium rounded-lg bg-white dark:bg-gray-800 text-gray-600 dark:text-gray-300 border border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700" data-category="{cat}" onclick="initCategoryFilter(\'{cat}\',this)">{label}</button>'
    return page_head(title, extra_css) + f'''<div class="mb-6">
<nav class="text-sm text-gray-500 dark:text-gray-400 mb-2" aria-label="Breadcrumb"><ol class="flex items-center gap-1.5"><li><a href="01-main-dashboard.html" class="hover:text-blue-600">Home</a></li><li class="before:content-['/'] before:mx-1.5 before:text-gray-300 dark:before:text-gray-600">UI Elements</li><li class="before:content-['/'] before:mx-1.5 before:text-gray-300 dark:before:text-gray-600 font-medium text-gray-800 dark:text-gray-200">{title}</li></ol></nav>
<div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h1 class="text-2xl font-bold text-gray-900 dark:text-white">{title}</h1><p class="text-gray-500 dark:text-gray-400 mt-1">{desc}</p></div>
<div class="relative"><input type="text" id="componentSearch" placeholder="Search…" class="pl-9 pr-4 py-2 text-sm border border-gray-200 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-800 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 w-56" oninput="initComponentSearch(this.value)"><svg class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg></div></div></div>
<div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">{stat_cards}</div>
<div class="flex flex-wrap gap-2 mb-6" id="categoryFilter">{cat_btns}</div>
<div class="grid grid-cols-1 lg:grid-cols-2 gap-6" id="componentGrid">{items_html}</div></div>''' + page_foot(extra_js)


# ====== AVATARS (123) ======
def gen_avatars():
    items = []
    items.append(ci("Basic Avatars", "Standard circular avatar images and initials", "basic", "bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300",
        '<div class="flex items-center gap-3"><div class="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center text-xs font-medium text-white">JD</div><div class="w-10 h-10 rounded-full bg-green-600 flex items-center justify-center text-sm font-medium text-white">AB</div><div class="w-12 h-12 rounded-full bg-purple-600 flex items-center justify-center text-base font-medium text-white">CD</div><div class="w-14 h-14 rounded-full bg-amber-600 flex items-center justify-center text-lg font-medium text-white">EF</div></div>',
        '<div class="w-10 h-10 rounded-full bg-blue-600 flex items-center justify-center text-sm font-medium text-white">AB</div>'))
    items.append(ci("Avatar with Image", "Photo-based avatars with fallback", "basic", "bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300",
        '<div class="flex items-center gap-3"><div class="w-10 h-10 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden flex items-center justify-center"><svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 24 24"><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/></svg></div><div class="w-10 h-10 rounded-full bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center text-blue-600 dark:text-blue-400 text-sm font-bold">AK</div><div class="w-10 h-10 rounded-full bg-rose-100 dark:bg-rose-900/30 flex items-center justify-center text-rose-600 dark:text-rose-400 text-sm font-bold">SM</div></div>',
        '<div class="w-10 h-10 rounded-full bg-gray-200 overflow-hidden"><img src="avatar.jpg" alt="User" /></div>'))
    items.append(ci("Avatar Status Indicator", "Online/offline/busy status dots", "status", "bg-green-50 dark:bg-green-900/30 text-green-700 dark:text-green-300",
        '<div class="flex items-center gap-4"><div class="relative"><div class="w-10 h-10 rounded-full bg-blue-600 flex items-center justify-center text-sm font-medium text-white">JD</div><span class="absolute bottom-0 right-0 w-3 h-3 bg-green-500 border-2 border-white dark:border-gray-900 rounded-full"></span></div><div class="relative"><div class="w-10 h-10 rounded-full bg-purple-600 flex items-center justify-center text-sm font-medium text-white">AB</div><span class="absolute bottom-0 right-0 w-3 h-3 bg-amber-500 border-2 border-white dark:border-gray-900 rounded-full"></span></div><div class="relative"><div class="w-10 h-10 rounded-full bg-rose-600 flex items-center justify-center text-sm font-medium text-white">CD</div><span class="absolute bottom-0 right-0 w-3 h-3 bg-gray-400 border-2 border-white dark:border-gray-900 rounded-full"></span></div></div>',
        '<div class="relative">\n  <div class="w-10 h-10 rounded-full bg-blue-600">JD</div>\n  <span class="absolute bottom-0 right-0 w-3 h-3 bg-green-500 border-2 border-white rounded-full"></span>\n</div>'))
    items.append(ci("Avatar Group / Stack", "Overlapping avatar stacks for teams", "group", "bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300",
        '<div class="flex items-center"><div class="w-10 h-10 rounded-full bg-blue-600 flex items-center justify-center text-sm font-medium text-white border-2 border-white dark:border-gray-900 -mr-2 relative z-30">JD</div><div class="w-10 h-10 rounded-full bg-green-600 flex items-center justify-center text-sm font-medium text-white border-2 border-white dark:border-gray-900 -mr-2 relative z-20">AB</div><div class="w-10 h-10 rounded-full bg-purple-600 flex items-center justify-center text-sm font-medium text-white border-2 border-white dark:border-gray-900 -mr-2 relative z-10">CD</div><div class="w-10 h-10 rounded-full bg-gray-200 dark:bg-gray-700 flex items-center justify-center text-xs font-medium text-gray-600 dark:text-gray-400 border-2 border-white dark:border-gray-900 relative">+5</div></div>',
        '<div class="flex items-center">\n  <div class="w-10 h-10 rounded-full border-2 border-white -mr-2 z-30">JD</div>\n  <div class="w-10 h-10 rounded-full border-2 border-white -mr-2 z-20">AB</div>\n  <div class="w-10 h-10 rounded-full border-2 border-white z-10">CD</div>\n  <div class="w-10 h-10 rounded-full bg-gray-200 border-2 border-white">+5</div>\n</div>'))
    items.append(ci("Avatar with Ring", "Highlight ring around avatar", "style", "bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300",
        '<div class="flex items-center gap-4"><div class="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center text-base font-medium text-white" style="box-shadow:0 0 0 3px #fff,0 0 0 5px #3b82f6">JD</div><div class="w-12 h-12 rounded-full bg-green-600 flex items-center justify-center text-base font-medium text-white" style="box-shadow:0 0 0 3px #fff,0 0 0 5px #10b981">AB</div><div class="w-12 h-12 rounded-full bg-rose-600 flex items-center justify-center text-base font-medium text-white" style="box-shadow:0 0 0 3px #fff,0 0 0 5px #f43f5e">CD</div></div>',
        '<div class="w-12 h-12 rounded-full bg-blue-600" style="box-shadow:0 0 0 3px #fff,0 0 0 5px #3b82f6">JD</div>'))
    items.append(ci("Square / Rounded Avatars", "Different border radius styles", "style", "bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300",
        '<div class="flex items-center gap-3"><div class="w-10 h-10 rounded-none bg-blue-600 flex items-center justify-center text-sm font-medium text-white">JD</div><div class="w-10 h-10 rounded-md bg-green-600 flex items-center justify-center text-sm font-medium text-white">AB</div><div class="w-10 h-10 rounded-lg bg-purple-600 flex items-center justify-center text-sm font-medium text-white">CD</div><div class="w-10 h-10 rounded-xl bg-amber-600 flex items-center justify-center text-sm font-medium text-white">EF</div><div class="w-10 h-10 rounded-full bg-rose-600 flex items-center justify-center text-sm font-medium text-white">GH</div></div>',
        '<div class="w-10 h-10 rounded-md bg-blue-600">JD</div>'))
    items.append(ci("Avatar Sizes", "From XS to XXL size variants", "basic", "bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300",
        '<div class="flex items-end gap-3"><div class="text-center"><div class="w-6 h-6 rounded-full bg-blue-600 flex items-center justify-center text-[8px] font-medium text-white">JD</div><p class="text-[10px] text-gray-400 mt-1">XS</p></div><div class="text-center"><div class="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center text-xs font-medium text-white">JD</div><p class="text-[10px] text-gray-400 mt-1">SM</p></div><div class="text-center"><div class="w-10 h-10 rounded-full bg-blue-600 flex items-center justify-center text-sm font-medium text-white">JD</div><p class="text-[10px] text-gray-400 mt-1">MD</p></div><div class="text-center"><div class="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center text-base font-medium text-white">JD</div><p class="text-[10px] text-gray-400 mt-1">LG</p></div><div class="text-center"><div class="w-16 h-16 rounded-full bg-blue-600 flex items-center justify-center text-xl font-medium text-white">JD</div><p class="text-[10px] text-gray-400 mt-1">XL</p></div></div>',
        '<div class="w-6 h-6 rounded-full bg-blue-600 text-[8px]">XS</div>\n<div class="w-10 h-10 rounded-full bg-blue-600 text-sm">MD</div>\n<div class="w-16 h-16 rounded-full bg-blue-600 text-xl">XL</div>'))
    items.append(ci("Avatar with Info", "Avatar paired with name and role", "group", "bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300",
        '<div class="flex items-center gap-3"><div class="w-10 h-10 rounded-full bg-blue-600 flex items-center justify-center text-sm font-medium text-white">JD</div><div><p class="text-sm font-medium text-gray-900 dark:text-white">Jane Doe</p><p class="text-xs text-gray-500 dark:text-gray-400">Product Designer</p></div></div><div class="flex items-center gap-3"><div class="w-10 h-10 rounded-full bg-green-600 flex items-center justify-center text-sm font-medium text-white">AK</div><div><p class="text-sm font-medium text-gray-900 dark:text-white">Alex Kim</p><p class="text-xs text-gray-500 dark:text-gray-400">Frontend Engineer</p></div></div>',
        '<div class="flex items-center gap-3">\n  <div class="w-10 h-10 rounded-full bg-blue-600">JD</div>\n  <div>\n    <p class="text-sm font-medium">Jane Doe</p>\n    <p class="text-xs text-gray-500">Product Designer</p>\n  </div>\n</div>'))
    
    html = wrap_page("Avatars", "8 avatar variants with live preview and source code",
        [{"label":"Variants","value":8,"sub":"4 categories","icon_bg":"bg-blue-50 dark:bg-blue-900/30","icon_color":"text-blue-600","icon_path":"M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"},
         {"label":"Sizes","value":5,"sub":"XS to XL","icon_bg":"bg-emerald-50 dark:bg-emerald-900/30","icon_color":"text-emerald-600","icon_path":"M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4"},
         {"label":"Shapes","value":5,"sub":"round/square/rounded","icon_bg":"bg-violet-50 dark:bg-violet-900/30","icon_color":"text-violet-600","icon_path":"M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12"},
         {"label":"Responsive","value":"100%","sub":"Mobile ready","icon_bg":"bg-amber-50 dark:bg-amber-900/30","icon_color":"text-amber-600","icon_path":"M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z"}],
        [("all","All"),("basic","Basic"),("status","Status"),("group","Group"),("style","Style")],
        '\n'.join(items))
    with open(os.path.join(BASE_DIR, "123-ui-avatars.html"), 'w') as f:
        f.write(html)
    print(f"Written 123-ui-avatars.html ({len(html)} bytes)")

# ====== BADGES (124) ======
def gen_badges():
    items = []
    items.append(ci("Status Badges", "Semantic status indicators", "status", "bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300",
        '<div class="flex flex-wrap gap-2"><span class="px-2.5 py-0.5 text-xs font-medium rounded-full bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400">Active</span><span class="px-2.5 py-0.5 text-xs font-medium rounded-full bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400">Pending</span><span class="px-2.5 py-0.5 text-xs font-medium rounded-full bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400">Inactive</span><span class="px-2.5 py-0.5 text-xs font-medium rounded-full bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-400">Info</span><span class="px-2.5 py-0.5 text-xs font-medium rounded-full bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300">Draft</span></div>',
        '<span class="px-2.5 py-0.5 text-xs font-medium rounded-full bg-green-100 text-green-700">Active</span>'))
    items.append(ci("Dot Badges", "Small colored dot indicators", "style", "bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300",
        '<div class="flex flex-wrap gap-3"><span class="flex items-center gap-1.5 text-sm text-gray-700 dark:text-gray-300"><span class="w-2 h-2 rounded-full bg-green-500"></span>Online</span><span class="flex items-center gap-1.5 text-sm text-gray-700 dark:text-gray-300"><span class="w-2 h-2 rounded-full bg-amber-500"></span>Away</span><span class="flex items-center gap-1.5 text-sm text-gray-700 dark:text-gray-300"><span class="w-2 h-2 rounded-full bg-red-500"></span>Busy</span><span class="flex items-center gap-1.5 text-sm text-gray-700 dark:text-gray-300"><span class="w-2 h-2 rounded-full bg-gray-400"></span>Offline</span></div>',
        '<span class="flex items-center gap-1.5"><span class="w-2 h-2 rounded-full bg-green-500"></span>Online</span>'))
    items.append(ci("Count Badges", "Notification and count indicators", "data", "bg-green-50 dark:bg-green-900/30 text-green-700 dark:text-green-300",
        '<div class="flex flex-wrap items-center gap-4"><div class="relative"><button class="p-2 text-gray-600 bg-gray-100 dark:bg-gray-700 rounded-lg"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"/></svg></button><span class="absolute -top-1 -right-1 w-5 h-5 bg-red-500 text-white text-[10px] font-bold rounded-full flex items-center justify-center">3</span></div><div class="relative"><button class="px-3 py-1.5 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg">Messages</button><span class="absolute -top-1.5 -right-1.5 px-1.5 py-0.5 bg-blue-600 text-white text-[10px] font-bold rounded-full">12</span></div></div>',
        '<div class="relative">\n  <button class="p-2 bg-gray-100 rounded-lg">🔔</button>\n  <span class="absolute -top-1 -right-1 w-5 h-5 bg-red-500 text-white text-[10px] rounded-full">3</span>\n</div>'))
    items.append(ci("Solid Badges", "Filled background badges", "style", "bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300",
        '<div class="flex flex-wrap gap-2"><span class="px-2.5 py-0.5 text-xs font-medium rounded-full text-white bg-blue-600">New</span><span class="px-2.5 py-0.5 text-xs font-medium rounded-full text-white bg-green-600">Pro</span><span class="px-2.5 py-0.5 text-xs font-medium rounded-full text-white bg-red-600">Hot</span><span class="px-2.5 py-0.5 text-xs font-medium rounded-full text-white bg-purple-600">Beta</span><span class="px-2.5 py-0.5 text-xs font-medium rounded-full text-white bg-amber-600">Sale</span></div>',
        '<span class="px-2.5 py-0.5 text-xs font-medium rounded-full text-white bg-blue-600">New</span>'))
    items.append(ci("Outlined Badges", "Border-only badge style", "style", "bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300",
        '<div class="flex flex-wrap gap-2"><span class="px-2.5 py-0.5 text-xs font-medium rounded-full text-blue-600 dark:text-blue-400 border border-blue-300 dark:border-blue-700">Info</span><span class="px-2.5 py-0.5 text-xs font-medium rounded-full text-green-600 dark:text-green-400 border border-green-300 dark:border-green-700">Success</span><span class="px-2.5 py-0.5 text-xs font-medium rounded-full text-red-600 dark:text-red-400 border border-red-300 dark:border-red-700">Error</span><span class="px-2.5 py-0.5 text-xs font-medium rounded-full text-amber-600 dark:text-amber-400 border border-amber-300 dark:border-amber-700">Warning</span></div>',
        '<span class="px-2.5 py-0.5 text-xs font-medium rounded-full text-blue-600 border border-blue-300">Info</span>'))
    items.append(ci("Tag / Label Badges", "Removable tags and labels", "data", "bg-green-50 dark:bg-green-900/30 text-green-700 dark:text-green-300",
        '<div class="flex flex-wrap gap-2"><span class="inline-flex items-center gap-1 px-2.5 py-1 text-xs font-medium bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300 rounded-lg">React <button class="hover:text-blue-900 dark:hover:text-blue-100"><svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg></button></span><span class="inline-flex items-center gap-1 px-2.5 py-1 text-xs font-medium bg-green-50 dark:bg-green-900/20 text-green-700 dark:text-green-300 rounded-lg">TypeScript <button class="hover:text-green-900 dark:hover:text-green-100"><svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg></button></span><span class="inline-flex items-center gap-1 px-2.5 py-1 text-xs font-medium bg-purple-50 dark:bg-purple-900/20 text-purple-700 dark:text-purple-300 rounded-lg">Tailwind <button class="hover:text-purple-900 dark:hover:text-purple-100"><svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg></button></span></div>',
        '<span class="inline-flex items-center gap-1 px-2.5 py-1 text-xs bg-blue-50 text-blue-700 rounded-lg">\n  React <button onclick="this.parentElement.remove()">×</button>\n</span>'))
    items.append(ci("Pill vs Rounded", "Different badge border radius styles", "style", "bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300",
        '<div class="flex flex-wrap gap-3"><span class="px-2.5 py-0.5 text-xs font-medium rounded bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300">Rounded</span><span class="px-2.5 py-0.5 text-xs font-medium rounded-full bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300">Pill</span><span class="px-2.5 py-0.5 text-xs font-medium rounded-md bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300">MD</span><span class="px-2.5 py-0.5 text-xs font-medium rounded-lg bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300">LG</span></div>',
        '<span class="px-2.5 py-0.5 text-xs font-medium rounded bg-blue-100 text-blue-700">Rounded</span>\n<span class="px-2.5 py-0.5 text-xs font-medium rounded-full bg-blue-100 text-blue-700">Pill</span>'))
    items.append(ci("Size Variants", "Badge sizes from XS to LG", "basic", "bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300",
        '<div class="flex flex-wrap items-center gap-3"><span class="px-1.5 py-0.5 text-[10px] font-medium rounded bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300">XS</span><span class="px-2 py-0.5 text-xs font-medium rounded bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300">SM</span><span class="px-2.5 py-0.5 text-sm font-medium rounded bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300">MD</span><span class="px-3 py-1 text-base font-medium rounded bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300">LG</span></div>',
        '<span class="px-1.5 py-0.5 text-[10px] rounded bg-blue-100 text-blue-700">XS</span>\n<span class="px-2.5 py-0.5 text-sm rounded bg-blue-100 text-blue-700">MD</span>'))
    
    html = wrap_page("Badges", "8 badge variants with live preview and source code",
        [{"label":"Variants","value":8,"sub":"4 categories","icon_bg":"bg-blue-50 dark:bg-blue-900/30","icon_color":"text-blue-600","icon_path":"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},
         {"label":"Colors","value":12,"sub":"semantic palette","icon_bg":"bg-emerald-50 dark:bg-emerald-900/30","icon_color":"text-emerald-600","icon_path":"M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4"},
         {"label":"Styles","value":4,"sub":"solid/soft/outlined/dot","icon_bg":"bg-violet-50 dark:bg-violet-900/30","icon_color":"text-violet-600","icon_path":"M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4"},
         {"label":"Responsive","value":"100%","sub":"Mobile ready","icon_bg":"bg-amber-50 dark:bg-amber-900/30","icon_color":"text-amber-600","icon_path":"M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z"}],
        [("all","All"),("basic","Basic"),("status","Status"),("style","Style"),("data","Data")],
        '\n'.join(items))
    with open(os.path.join(BASE_DIR, "124-ui-badge.html"), 'w') as f:
        f.write(html)
    print(f"Written 124-ui-badge.html ({len(html)} bytes)")

# ====== BREADCRUMB (125) ======
def gen_breadcrumb():
    items = []
    items.append(ci("Basic Breadcrumb", "Standard slash-separated navigation trail", "basic", "bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300",
        '<nav aria-label="Breadcrumb"><ol class="flex items-center gap-1.5 text-sm"><li class="text-gray-500 dark:text-gray-400">Home</li><li class="text-gray-300 dark:text-gray-600">/</li><li class="text-gray-500 dark:text-gray-400">Products</li><li class="text-gray-300 dark:text-gray-600">/</li><li class="font-medium text-gray-900 dark:text-white">Laptop Pro</li></ol></nav>',
        '<nav aria-label="Breadcrumb"><ol class="flex items-center gap-1.5 text-sm">\n  <li class="text-gray-500">Home</li>\n  <li class="text-gray-300">/</li>\n  <li class="text-gray-500">Products</li>\n  <li class="text-gray-300">/</li>\n  <li class="font-medium text-gray-900">Laptop Pro</li>\n</ol></nav>'))
    items.append(ci("Chevron Breadcrumb", "Using chevron icons as separators", "style", "bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300",
        '<nav aria-label="Breadcrumb"><ol class="flex items-center gap-1.5 text-sm"><li><a href="#" class="text-gray-500 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">Home</a></li><li><svg class="w-4 h-4 text-gray-300 dark:text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg></li><li><a href="#" class="text-gray-500 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">Dashboard</a></li><li><svg class="w-4 h-4 text-gray-300 dark:text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg></li><li class="font-medium text-gray-900 dark:text-white">Analytics</li></ol></nav>',
        '<nav><ol class="flex items-center gap-1.5 text-sm">\n  <li><a href="#" class="text-gray-500 hover:text-blue-600">Home</a></li>\n  <li><svg class="w-4 h-4 text-gray-300">›</svg></li>\n  <li class="font-medium">Analytics</li>\n</ol></nav>'))
    items.append(ci("Breadcrumb with Icons", "Items with icon prefixes", "style", "bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300",
        '<nav aria-label="Breadcrumb"><ol class="flex items-center gap-2 text-sm"><li><a href="#" class="flex items-center gap-1 text-gray-500 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-400"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-4 0h4"/></svg>Home</a></li><li class="text-gray-300 dark:text-gray-600">/</li><li><a href="#" class="flex items-center gap-1 text-gray-500 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-400"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"/></svg>Projects</a></li><li class="text-gray-300 dark:text-gray-600">/</li><li class="font-medium text-gray-900 dark:text-white">Design System</li></ol></nav>',
        '<nav><ol class="flex items-center gap-2 text-sm">\n  <li><a href="#" class="flex items-center gap-1 text-gray-500">🏠 Home</a></li>\n  <li>/</li>\n  <li><a href="#" class="flex items-center gap-1 text-gray-500">📁 Projects</a></li>\n  <li>/</li>\n  <li class="font-medium">Design System</li>\n</ol></nav>'))
    items.append(ci("Pill Breadcrumb", "Breadcrumb items in pill-shaped containers", "style", "bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300",
        '<nav aria-label="Breadcrumb"><ol class="flex items-center gap-1.5"><li><a href="#" class="px-3 py-1 text-xs font-medium text-gray-600 dark:text-gray-400 bg-gray-100 dark:bg-gray-800 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors">Home</a></li><li class="text-gray-300 dark:text-gray-600"><svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg></li><li><a href="#" class="px-3 py-1 text-xs font-medium text-gray-600 dark:text-gray-400 bg-gray-100 dark:bg-gray-800 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors">Settings</a></li><li class="text-gray-300 dark:text-gray-600"><svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg></li><li class="px-3 py-1 text-xs font-medium text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/20 rounded-full">Profile</li></ol></nav>',
        '<nav><ol class="flex items-center gap-1.5">\n  <li><a class="px-3 py-1 text-xs bg-gray-100 rounded-full">Home</a></li>\n  <li>›</li>\n  <li><a class="px-3 py-1 text-xs bg-gray-100 rounded-full">Settings</a></li>\n  <li>›</li>\n  <li class="px-3 py-1 text-xs bg-blue-50 rounded-full">Profile</li>\n</ol></nav>'))
    items.append(ci("Dark Background Breadcrumb", "Breadcrumb on dark or colored backgrounds", "style", "bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300",
        '<div class="bg-gray-900 rounded-lg px-4 py-3"><nav aria-label="Breadcrumb"><ol class="flex items-center gap-1.5 text-sm"><li><a href="#" class="text-gray-400 hover:text-white transition-colors">Home</a></li><li class="text-gray-600">/</li><li><a href="#" class="text-gray-400 hover:text-white transition-colors">Account</a></li><li class="text-gray-600">/</li><li class="font-medium text-white">Settings</li></ol></nav></div>',
        '<div class="bg-gray-900 rounded-lg px-4 py-3">\n  <nav><ol class="flex items-center gap-1.5 text-sm">\n    <li><a class="text-gray-400 hover:text-white">Home</a></li>\n    <li class="text-gray-600">/</li>\n    <li class="font-medium text-white">Settings</li>\n  </ol></nav>\n</div>'))
    
    html = wrap_page("Breadcrumb", "5 breadcrumb variants with live preview and source code",
        [{"label":"Variants","value":5,"sub":"2 categories","icon_bg":"bg-blue-50 dark:bg-blue-900/30","icon_color":"text-blue-600","icon_path":"M3 12l2-2m0 0l7-7 7 7"},
         {"label":"Separators","value":3,"sub":"slash/chevron/arrow","icon_bg":"bg-emerald-50 dark:bg-emerald-900/30","icon_color":"text-emerald-600","icon_path":"M9 5l7 7-7 7"},
         {"label":"Styles","value":2,"sub":"standard/pill","icon_bg":"bg-violet-50 dark:bg-violet-900/30","icon_color":"text-violet-600","icon_path":"M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4"},
         {"label":"Responsive","value":"100%","sub":"Mobile ready","icon_bg":"bg-amber-50 dark:bg-amber-900/30","icon_color":"text-amber-600","icon_path":"M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z"}],
        [("all","All"),("basic","Basic"),("style","Style")],
        '\n'.join(items))
    with open(os.path.join(BASE_DIR, "125-ui-breadcrumb.html"), 'w') as f:
        f.write(html)
    print(f"Written 125-ui-breadcrumb.html ({len(html)} bytes)")

# ====== NOTIFICATIONS (134) ======
def gen_notifications():
    items = []
    items.append(ci("Info Alert", "Standard informational notification", "basic", "bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300",
        '<div class="w-full"><div class="flex items-start gap-3 p-4 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg"><svg class="w-5 h-5 text-blue-600 dark:text-blue-400 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg><div class="flex-1"><p class="text-sm font-medium text-blue-800 dark:text-blue-300">Update available</p><p class="text-sm text-blue-700 dark:text-blue-400 mt-0.5">A new version of the application is ready to install.</p></div><button class="text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-200"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg></button></div></div>',
        '<div class="flex items-start gap-3 p-4 bg-blue-50 border border-blue-200 rounded-lg">\n  <svg class="w-5 h-5 text-blue-600">ℹ</svg>\n  <div><p class="font-medium text-blue-800">Update available</p></div>\n  <button class="text-blue-600 hover:text-blue-800">×</button>\n</div>'))
    items.append(ci("Success Alert", "Positive outcome notification", "status", "bg-green-50 dark:bg-green-900/30 text-green-700 dark:text-green-300",
        '<div class="w-full"><div class="flex items-start gap-3 p-4 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-lg"><svg class="w-5 h-5 text-green-600 dark:text-green-400 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg><div class="flex-1"><p class="text-sm font-medium text-green-800 dark:text-green-300">Changes saved</p><p class="text-sm text-green-700 dark:text-green-400 mt-0.5">Your profile has been updated successfully.</p></div><button class="text-green-600 dark:text-green-400 hover:text-green-800 dark:hover:text-green-200"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg></button></div></div>',
        '<div class="flex items-start gap-3 p-4 bg-green-50 border border-green-200 rounded-lg">\n  <svg class="text-green-600">✓</svg>\n  <p class="font-medium text-green-800">Changes saved</p>\n</div>'))
    items.append(ci("Warning Alert", "Caution and attention notifications", "status", "bg-amber-50 dark:bg-amber-900/30 text-amber-700 dark:text-amber-300",
        '<div class="w-full"><div class="flex items-start gap-3 p-4 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg"><svg class="w-5 h-5 text-amber-600 dark:text-amber-400 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z"/></svg><div class="flex-1"><p class="text-sm font-medium text-amber-800 dark:text-amber-300">SSL certificate expiring</p><p class="text-sm text-amber-700 dark:text-amber-400 mt-0.5">Your certificate will expire in 7 days. Please renew it to avoid service interruption.</p></div><button class="text-amber-600 dark:text-amber-400 hover:text-amber-800 dark:hover:text-amber-200"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg></button></div></div>',
        '<div class="flex items-start gap-3 p-4 bg-amber-50 border border-amber-200 rounded-lg">\n  <svg class="text-amber-600">⚠</svg>\n  <p class="font-medium text-amber-800">SSL certificate expiring</p>\n</div>'))
    items.append(ci("Error Alert", "Error and failure notifications", "status", "bg-red-50 dark:bg-red-900/30 text-red-700 dark:text-red-300",
        '<div class="w-full"><div class="flex items-start gap-3 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg"><svg class="w-5 h-5 text-red-600 dark:text-red-400 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg><div class="flex-1"><p class="text-sm font-medium text-red-800 dark:text-red-300">Payment failed</p><p class="text-sm text-red-700 dark:text-red-400 mt-0.5">Your card was declined. Please update your payment method and try again.</p></div><button class="text-red-600 dark:text-red-400 hover:text-red-800 dark:hover:text-red-200"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg></button></div></div>',
        '<div class="flex items-start gap-3 p-4 bg-red-50 border border-red-200 rounded-lg">\n  <svg class="text-red-600">✕</svg>\n  <p class="font-medium text-red-800">Payment failed</p>\n</div>'))
    items.append(ci("Toast Notifications", "Auto-dismissing popup notifications", "toast", "bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300",
        '<div class="w-full flex flex-col gap-3"><div class="flex items-center gap-3 px-4 py-3 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg shadow-sm max-w-sm"><span class="w-8 h-8 rounded-full bg-green-100 dark:bg-green-900/30 flex items-center justify-center flex-shrink-0"><svg class="w-4 h-4 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg></span><div class="flex-1"><p class="text-sm font-medium text-gray-900 dark:text-white">Saved</p></div><button class="text-gray-400 hover:text-gray-600"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg></button></div><div class="flex items-center gap-3 px-4 py-3 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg shadow-sm max-w-sm"><span class="w-8 h-8 rounded-full bg-red-100 dark:bg-red-900/30 flex items-center justify-center flex-shrink-0"><svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg></span><div class="flex-1"><p class="text-sm font-medium text-gray-900 dark:text-white">Error occurred</p></div><button class="text-gray-400 hover:text-gray-600"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg></button></div></div>',
        '<div class="fixed top-4 right-4 z-50">\n  <div class="flex items-center gap-3 px-4 py-3 bg-white border rounded-lg shadow-sm">\n    <span class="icon">✓</span>\n    <p class="font-medium">Saved</p>\n    <button>×</button>\n  </div>\n</div>'))
    items.append(ci("Alert with Action", "Notification with action button", "action", "bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300",
        '<div class="w-full"><div class="flex items-start gap-3 p-4 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg"><svg class="w-5 h-5 text-blue-600 dark:text-blue-400 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg><div class="flex-1"><p class="text-sm font-medium text-blue-800 dark:text-blue-300">New feature available</p><p class="text-sm text-blue-700 dark:text-blue-400 mt-0.5">Custom themes are now available in your settings.</p><div class="mt-2"><button class="px-3 py-1 text-xs font-medium text-blue-700 dark:text-blue-300 bg-blue-100 dark:bg-blue-900/40 rounded hover:bg-blue-200 dark:hover:bg-blue-900/60 transition-colors">Enable Themes</button></div></div></div></div>',
        '<div class="p-4 bg-blue-50 border border-blue-200 rounded-lg">\n  <p class="font-medium">New feature available</p>\n  <p class="text-sm mt-0.5">Custom themes are now available.</p>\n  <button class="mt-2 px-3 py-1 text-xs bg-blue-100 rounded">Enable Themes</button>\n</div>'))
    
    html = wrap_page("Notifications", "6 notification variants with live preview and source code",
        [{"label":"Variants","value":6,"sub":"4 categories","icon_bg":"bg-blue-50 dark:bg-blue-900/30","icon_color":"text-blue-600","icon_path":"M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341"},
         {"label":"Colors","value":4,"sub":"info/success/warn/error","icon_bg":"bg-emerald-50 dark:bg-emerald-900/30","icon_color":"text-emerald-600","icon_path":"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},
         {"label":"Placements","value":3,"sub":"inline/toast/banner","icon_bg":"bg-violet-50 dark:bg-violet-900/30","icon_color":"text-violet-600","icon_path":"M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4"},
         {"label":"Responsive","value":"100%","sub":"Mobile ready","icon_bg":"bg-amber-50 dark:bg-amber-900/30","icon_color":"text-amber-600","icon_path":"M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z"}],
        [("all","All"),("basic","Basic"),("status","Status"),("toast","Toast"),("action","Action")],
        '\n'.join(items))
    with open(os.path.join(BASE_DIR, "134-ui-notifications.html"), 'w') as f:
        f.write(html)
    print(f"Written 134-ui-notifications.html ({len(html)} bytes)")

# ====== TOOLTIPS (141) ======
def gen_tooltips():
    items = []
    items.append(ci("Top Tooltip", "Default tooltip appearing above element", "basic", "bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300",
        '<div class="flex gap-6 justify-center py-4"><div class="relative group"><button class="px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg">Hover me</button><div class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-2.5 py-1 text-xs font-medium text-white bg-gray-900 rounded-md opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap pointer-events-none">Tooltip on top<div class="absolute top-full left-1/2 -translate-x-1/2 w-2 h-2 bg-gray-900 rotate-45 -mt-1"></div></div></div></div>',
        '<div class="relative group">\n  <button>Hover me</button>\n  <div class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-2.5 py-1 text-xs bg-gray-900 text-white rounded-md opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap pointer-events-none">Tooltip on top</div>\n</div>'))
    items.append(ci("Bottom Tooltip", "Tooltip appearing below element", "basic", "bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300",
        '<div class="flex gap-6 justify-center py-8"><div class="relative group"><button class="px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg">Below</button><div class="absolute top-full left-1/2 -translate-x-1/2 mt-2 px-2.5 py-1 text-xs font-medium text-white bg-gray-900 rounded-md opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap pointer-events-none">Tooltip on bottom</div></div></div>',
        '<div class="relative group">\n  <button>Below</button>\n  <div class="absolute top-full left-1/2 -translate-x-1/2 mt-2 px-2.5 py-1 text-xs bg-gray-900 text-white rounded-md opacity-0 group-hover:opacity-100">Below</div>\n</div>'))
    items.append(ci("Left / Right Tooltips", "Side-positioned tooltips", "basic", "bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300",
        '<div class="flex gap-8 justify-center py-4"><div class="relative group"><button class="px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg">Left</button><div class="absolute right-full top-1/2 -translate-y-1/2 mr-2 px-2.5 py-1 text-xs font-medium text-white bg-gray-900 rounded-md opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap pointer-events-none">Left tooltip</div></div><div class="relative group"><button class="px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg">Right</button><div class="absolute left-full top-1/2 -translate-y-1/2 ml-2 px-2.5 py-1 text-xs font-medium text-white bg-gray-900 rounded-md opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap pointer-events-none">Right tooltip</div></div></div>',
        '<!-- Left -->\n<div class="absolute right-full top-1/2 -translate-y-1/2 mr-2">Left tooltip</div>\n<!-- Right -->\n<div class="absolute left-full top-1/2 -translate-y-1/2 ml-2">Right tooltip</div>'))
    items.append(ci("Light Tooltip", "Light background tooltip variant", "style", "bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300",
        '<div class="flex gap-6 justify-center py-4"><div class="relative group"><button class="px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg">Light tooltip</button><div class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-2.5 py-1 text-xs font-medium text-gray-800 bg-white border border-gray-200 rounded-md shadow-sm opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap pointer-events-none">Light variant</div></div></div>',
        '<div class="px-2.5 py-1 text-xs text-gray-800 bg-white border border-gray-200 rounded-md shadow-sm">Light variant</div>'))
    items.append(ci("Multi-line Tooltip", "Tooltip with longer description text", "data", "bg-green-50 dark:bg-green-900/30 text-green-700 dark:text-green-300",
        '<div class="flex gap-6 justify-center py-4"><div class="relative group"><button class="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg">More info</button><div class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-3 py-2 text-xs text-white bg-gray-900 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity w-56 pointer-events-none"><p class="font-medium mb-1">Detailed Information</p><p class="text-gray-300">This tooltip contains multiple lines of helpful description text for the user.</p></div></div></div>',
        '<div class="px-3 py-2 text-xs text-white bg-gray-900 rounded-lg w-56">\n  <p class="font-medium mb-1">Detailed Information</p>\n  <p class="text-gray-300">This tooltip contains multiple lines.</p>\n</div>'))
    
    html = wrap_page("Tooltips", "5 tooltip variants with live preview and source code",
        [{"label":"Variants","value":5,"sub":"3 categories","icon_bg":"bg-blue-50 dark:bg-blue-900/30","icon_color":"text-blue-600","icon_path":"M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"},
         {"label":"Positions","value":4,"sub":"top/bottom/left/right","icon_bg":"bg-emerald-50 dark:bg-emerald-900/30","icon_color":"text-emerald-600","icon_path":"M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5"},
         {"label":"Styles","value":2,"sub":"dark/light","icon_bg":"bg-violet-50 dark:bg-violet-900/30","icon_color":"text-violet-600","icon_path":"M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4"},
         {"label":"Responsive","value":"100%","sub":"Mobile ready","icon_bg":"bg-amber-50 dark:bg-amber-900/30","icon_color":"text-amber-600","icon_path":"M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z"}],
        [("all","All"),("basic","Basic"),("style","Style"),("data","Data")],
        '\n'.join(items))
    with open(os.path.join(BASE_DIR, "141-ui-tooltips.html"), 'w') as f:
        f.write(html)
    print(f"Written 141-ui-tooltips.html ({len(html)} bytes)")

# ====== SPINNERS (139) ======
def gen_spinners():
    items = []
    items.append(ci("Border Spinner", "Classic rotating border spinner", "basic", "bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300",
        '<div class="flex items-center gap-6"><div class="w-5 h-5 border-2 border-gray-200 dark:border-gray-600 border-t-blue-600 rounded-full animate-spin"></div><div class="w-8 h-8 border-[3px] border-gray-200 dark:border-gray-600 border-t-blue-600 rounded-full animate-spin"></div><div class="w-12 h-12 border-4 border-gray-200 dark:border-gray-600 border-t-blue-600 rounded-full animate-spin"></div></div>',
        '<div class="w-8 h-8 border-[3px] border-gray-200 border-t-blue-600 rounded-full animate-spin"></div>'))
    items.append(ci("SVG Circle Spinner", "SVG-based spinner animation", "style", "bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300",
        '<div class="flex items-center gap-6"><svg class="w-6 h-6 animate-spin text-blue-600" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path></svg><svg class="w-10 h-10 animate-spin text-green-600" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path></svg></div>',
        '<svg class="w-8 h-8 animate-spin text-blue-600" fill="none" viewBox="0 0 24 24">\n  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/>\n  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>\n</svg>'))
    items.append(ci("Dots Spinner", "Bouncing dots loading indicator", "style", "bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300",
        '<div class="flex items-center gap-2"><div class="w-2 h-2 bg-blue-600 rounded-full animate-bounce" style="animation-delay:0ms"></div><div class="w-2 h-2 bg-blue-600 rounded-full animate-bounce" style="animation-delay:150ms"></div><div class="w-2 h-2 bg-blue-600 rounded-full animate-bounce" style="animation-delay:300ms"></div></div>',
        '<div class="flex items-center gap-2">\n  <div class="w-2 h-2 bg-blue-600 rounded-full animate-bounce" style="animation-delay:0ms"></div>\n  <div class="w-2 h-2 bg-blue-600 rounded-full animate-bounce" style="animation-delay:150ms"></div>\n  <div class="w-2 h-2 bg-blue-600 rounded-full animate-bounce" style="animation-delay:300ms"></div>\n</div>'))
    items.append(ci("Pulse Spinner", "Pulsing circle loading animation", "style", "bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300",
        '<div class="flex items-center gap-6"><div class="w-4 h-4 bg-blue-600 rounded-full animate-pulse"></div><div class="w-6 h-6 bg-green-600 rounded-full animate-pulse"></div><div class="w-8 h-8 bg-purple-600 rounded-full animate-pulse"></div></div>',
        '<div class="w-4 h-4 bg-blue-600 rounded-full animate-pulse"></div>'))
    items.append(ci("Color Variants", "Spinners in different colors", "basic", "bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300",
        '<div class="flex items-center gap-6"><div class="w-8 h-8 border-[3px] border-gray-200 dark:border-gray-600 border-t-blue-600 rounded-full animate-spin"></div><div class="w-8 h-8 border-[3px] border-gray-200 dark:border-gray-600 border-t-green-600 rounded-full animate-spin"></div><div class="w-8 h-8 border-[3px] border-gray-200 dark:border-gray-600 border-t-red-600 rounded-full animate-spin"></div><div class="w-8 h-8 border-[3px] border-gray-200 dark:border-gray-600 border-t-amber-500 rounded-full animate-spin"></div><div class="w-8 h-8 border-[3px] border-gray-200 dark:border-gray-600 border-t-purple-600 rounded-full animate-spin"></div></div>',
        '<div class="w-8 h-8 border-[3px] border-gray-200 border-t-blue-600 rounded-full animate-spin"></div>\n<!-- Use border-t-green-600, border-t-red-600, etc. -->'))
    items.append(ci("Loading with Text", "Spinner paired with loading message", "data", "bg-green-50 dark:bg-green-900/30 text-green-700 dark:text-green-300",
        '<div class="flex flex-col gap-4"><div class="flex items-center gap-3"><div class="w-5 h-5 border-2 border-gray-200 dark:border-gray-600 border-t-blue-600 rounded-full animate-spin"></div><span class="text-sm text-gray-600 dark:text-gray-400">Loading data…</span></div><div class="flex items-center gap-3"><svg class="w-5 h-5 animate-spin text-blue-600" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path></svg><span class="text-sm text-gray-600 dark:text-gray-400">Saving changes…</span></div></div>',
        '<div class="flex items-center gap-3">\n  <div class="w-5 h-5 border-2 border-gray-200 border-t-blue-600 rounded-full animate-spin"></div>\n  <span class="text-sm text-gray-600">Loading data…</span>\n</div>'))
    items.append(ci("Full Page Loader", "Centered full-page loading overlay", "data", "bg-green-50 dark:bg-green-900/30 text-green-700 dark:text-green-300",
        '<div class="w-full h-40 bg-gray-100 dark:bg-gray-800 rounded-lg flex items-center justify-center"><div class="text-center"><svg class="w-10 h-10 animate-spin text-blue-600 mx-auto mb-3" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path></svg><p class="text-sm font-medium text-gray-600 dark:text-gray-400">Loading application…</p><p class="text-xs text-gray-400 dark:text-gray-500 mt-1">This won't take long</p></div></div>',
        '<div class="fixed inset-0 bg-white/80 dark:bg-gray-900/80 flex items-center justify-center z-50">\n  <div class="text-center">\n    <svg class="w-10 h-10 animate-spin text-blue-600 mx-auto mb-3">…</svg>\n    <p class="text-sm font-medium text-gray-600">Loading…</p>\n  </div>\n</div>'))
    
    html = wrap_page("Spinners", "7 spinner variants with live preview and source code",
        [{"label":"Variants","value":7,"sub":"3 categories","icon_bg":"bg-blue-50 dark:bg-blue-900/30","icon_color":"text-blue-600","icon_path":"M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"},
         {"label":"Colors","value":5,"sub":"blue/green/red/amber/purple","icon_bg":"bg-emerald-50 dark:bg-emerald-900/30","icon_color":"text-emerald-600","icon_path":"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},
         {"label":"Sizes","value":3,"sub":"sm/md/lg","icon_bg":"bg-violet-50 dark:bg-violet-900/30","icon_color":"text-violet-600","icon_path":"M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4"},
         {"label":"Responsive","value":"100%","sub":"Mobile ready","icon_bg":"bg-amber-50 dark:bg-amber-900/30","icon_color":"text-amber-600","icon_path":"M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z"}],
        [("all","All"),("basic","Basic"),("style","Style"),("data","Data")],
        '\n'.join(items))
    with open(os.path.join(BASE_DIR, "139-ui-spinners.html"), 'w') as f:
        f.write(html)
    print(f"Written 139-ui-spinners.html ({len(html)} bytes)")

# ====== PAGINATION (135) ======
def gen_pagination():
    items = []
    items.append(ci("Basic Pagination", "Standard page number navigation", "basic", "bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300",
        '<nav class="inline-flex items-center gap-1"><button class="px-3 py-1.5 text-sm text-gray-400 dark:text-gray-500 cursor-not-allowed" disabled>← Prev</button><button class="px-3 py-1.5 text-sm font-medium text-white bg-blue-600 rounded-md">1</button><button class="px-3 py-1.5 text-sm text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md">2</button><button class="px-3 py-1.5 text-sm text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md">3</button><span class="px-2 text-gray-400">…</span><button class="px-3 py-1.5 text-sm text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md">12</button><button class="px-3 py-1.5 text-sm text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md">Next →</button></nav>',
        '<nav class="inline-flex items-center gap-1">\n  <button disabled>← Prev</button>\n  <button class="bg-blue-600 text-white rounded-md">1</button>\n  <button class="hover:bg-gray-100 rounded-md">2</button>\n  <button>3</button>\n  <span>…</span>\n  <button>12</button>\n  <button>Next →</button>\n</nav>'))
    items.append(ci("Icon Pagination", "Prev/next with arrow icons", "style", "bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300",
        '<nav class="inline-flex items-center gap-1"><button class="p-2 text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/></svg></button><button class="px-3 py-1.5 text-sm font-medium text-white bg-blue-600 rounded-md">1</button><button class="px-3 py-1.5 text-sm text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md">2</button><button class="px-3 py-1.5 text-sm text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md">3</button><button class="p-2 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg></button></nav>',
        '<nav class="inline-flex items-center gap-1">\n  <button class="p-2"><svg>←</svg></button>\n  <button class="bg-blue-600 text-white">1</button>\n  <button>2</button>\n  <button class="p-2"><svg>→</svg></button>\n</nav>'))
    items.append(ci("Compact Pagination", "Minimal pagination for small spaces", "style", "bg-violet-50 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300",
        '<div class="flex items-center gap-3 text-sm"><button class="text-gray-500 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">Previous</button><span class="text-gray-400">|</span><span class="text-gray-600 dark:text-gray-400">Page <strong class="text-gray-900 dark:text-white">2</strong> of 12</span><span class="text-gray-400">|</span><button class="text-gray-500 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">Next</button></div>',
        '<div class="flex items-center gap-3 text-sm">\n  <button class="text-gray-500">Previous</button>\n  <span>Page <strong>2</strong> of 12</span>\n  <button class="text-gray-500">Next</button>\n</div>'))
    items.append(ci("Table Pagination", "Pagination with page size selector for data tables", "data", "bg-green-50 dark:bg-green-900/30 text-green-700 dark:text-green-300",
        '<div class="flex items-center justify-between"><div class="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400"><span>Show</span><select class="px-2 py-1 text-sm border border-gray-200 dark:border-gray-600 rounded bg-white dark:bg-gray-800"><option>10</option><option>25</option><option>50</option></select><span>of 248</span></div><nav class="inline-flex items-center gap-1"><button class="p-1.5 text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/></svg></button><button class="px-2.5 py-1 text-sm font-medium text-white bg-blue-600 rounded">1</button><button class="px-2.5 py-1 text-sm text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded">2</button><button class="px-2.5 py-1 text-sm text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded">3</button><button class="p-1.5 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg></button></nav></div>',
        '<div class="flex items-center justify-between">\n  <div class="text-sm text-gray-500">\n    Show <select>10</select> of 248\n  </div>\n  <nav>1 2 3 →</nav>\n</div>'))
    items.append(ci("Load More Button", "Progressive loading pattern", "data", "bg-green-50 dark:bg-green-900/30 text-green-700 dark:text-green-300",
        '<div class="text-center"><button class="px-6 py-2.5 text-sm font-medium text-blue-600 border border-blue-600 rounded-lg hover:bg-blue-50 dark:hover:bg-blue-900/20 transition-colors">Load More</button><p class="text-xs text-gray-400 mt-2">Showing 20 of 148 items</p></div>',
        '<div class="text-center">\n  <button class="px-6 py-2.5 text-sm text-blue-600 border border-blue-600 rounded-lg hover:bg-blue-50">Load More</button>\n  <p class="text-xs text-gray-400 mt-2">Showing 20 of 148 items</p>\n</div>'))
    
    html = wrap_page("Pagination", "5 pagination variants with live preview and source code",
        [{"label":"Variants","value":5,"sub":"3 categories","icon_bg":"bg-blue-50 dark:bg-blue-900/30","icon_color":"text-blue-600","icon_path":"M4 6h16M4 12h16M4 18h7"},
         {"label":"Styles","value":3,"sub":"numbered/icon/compact","icon_bg":"bg-emerald-50 dark:bg-emerald-900/30","icon_color":"text-emerald-600","icon_path":"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},
         {"label":"Features","value":2,"sub":"page-size/load-more","icon_bg":"bg-violet-50 dark:bg-violet-900/30","icon_color":"text-violet-600","icon_path":"M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4"},
         {"label":"Responsive","value":"100%","sub":"Mobile ready","icon_bg":"bg-amber-50 dark:bg-amber-900/30","icon_color":"text-amber-600","icon_path":"M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z"}],
        [("all","All"),("basic","Basic"),("style","Style"),("data","Data")],
        '\n'.join(items))
    with open(os.path.join(BASE_DIR, "135-ui-pagination.html"), 'w') as f:
        f.write(html)
    print(f"Written 135-ui-pagination.html ({len(html)} bytes)")

# Run all generators
if __name__ == "__main__":
    gen_avatars()
    gen_badges()
    gen_breadcrumb()
    gen_notifications()
    gen_tooltips()
    gen_spinners()
    gen_pagination()
    print("All batch 2 UI pages generated!")
